### ISSUE TITLE
Dependency "Go-Redis" lacks folder "/v7/"

### ISSUE THREAD

**Issue by JohnLins** [rditech/rdi-live#8]
RdiLive requires the dependency "Go-Redis" When I try to install this dependency @ github.com/go-redis/redis/v7/... it did not work because the folder "/v7/" does not exist in the repo: github.com/go-redis/redis/. The lack of this dependency is preventing me from successfully running the application.
Please let me know what's wrong here.
Thanks

**Comment by decibelcooper** [comment]
Hello @JohnLins 

Can you please tell me what version of `go` you're using, and give me a description of the commands you're using and errors you're encountering?

**Comment by JohnLins** [comment]
Yeah, I'm using Go version 1.8.3. I installed all of Rdi's dependencies, but go-redis/redis does not have the folder "v7". A few other errors popped up. Please take a look at the screenshot: 
![Annotation 2020-03-03 161415](https://user-images.githubusercontent.com/46113320/75832076-1648ae80-5d6a-11ea-9468-2d955c55cb93.png)

**Comment by decibelcooper** [comment]
@JohnLins please install version 1.11 or newer as specified in the `README.md` under "Tools Installation".  I recommend getting the very latest 1.14 from [here](https://golang.org/dl/).  With newer version of go, "subdirectories" of public repositories that are of the form "v7" are interpreted as pointing towards release tags, not actual subdirectories.

**Comment by JohnLins** [comment]
Hi David,
My bad, when I read "1.11" my brain somehow told me "1.1.1" haha. 
I'm all up and running now, thanks for bearing with my stupidity.
Regards,
John

**Comment by decibelcooper** [comment]
@JohnLins no worries at all.  The go toolchain is a bit different and requires some getting used to.
